### ISSUE TITLE
Create Clone.sh Script

### ISSUE THREAD

**Issue by josefcoap** [ElrondNetwork/elrond-go-scripts#1]
It can be interesting to have a new script here. Specially for people that wants 2-3 nodes in a machine/vps.

The script must clone setup folder and node executable. Create new pair of keys and move them into setup I guess.

It must be someway compatible with update script

**Comment by ahakla** [comment]
Hi Josef, I wrote a script that isn't yet compatible with the update script, but it's a start!

See https://github.com/ElrondNetwork/elrond-go-scripts/pull/7.

**Comment by josefcoap** [comment]
I will close this issue, @ahakla has worked on really better solution for this
