### ISSUE TITLE
Use curl to get latest tags

### ISSUE THREAD

**Issue by ahakla** [ElrondNetwork/elrond-go-scripts#19]
In the install.sh script, use:

`BINARY_VER="tags/$(curl --silent "https://api.github.com/repos/ElrondNetwork/elrond-go/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')"`
`CONFIG_VER="tags/$(curl --silent "https://api.github.com/repos/ElrondNetwork/elrond-config/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')"`

**Comment by valentin-lup** [comment]
We were debating if we want to add this automation ourselves. Since someone from the community felt that it is a good idea too will add this to the scripts.

**Comment by valentin-lup** [comment]
Update - added the change to both install & update scripts.

**Comment by ahakla** [comment]
Thank you Valentin!
