### ISSUE TITLE
Don't automatically start the node right after install / update

### ISSUE THREAD

**Issue by ahakla** [ElrondNetwork/elrond-go-scripts#8]
In the current install.sh and update.sh scripts, the node is automatically started right after installation/update.

I don't think this is a good idea, because people might want to copy their backed up .pem files to their node config folder first, after a clean install.

A start.sh script is already available, so I would not add this auto-start to the install.sh and update.sh scripts.

**Comment by valentin-lup** [comment]
Solved in latest version of the scripts. Good call.
